blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for SwitchBot
    url: https://discord.gg/5wYTbwP4ha
    about: Please ask and answer questions here.
  - name: Homebridge Switchbot Openapi - Pull Requests
    url: https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/pulls
    about: Please report security vulnerabilities here.
